### ISSUE TITLE
Include raw numbers instead of percentages, if possible?

### ISSUE THREAD

**Issue by dannguyen** [sashaperigo/csprof-diversity-data#7]
Some reports probably only include percentage breakdowns. But others include raw numbers. And still others include both, [such as in MIT's report](http://web.mit.edu/provost/raceinitiative/report.pdf):

![image](https://cloud.githubusercontent.com/assets/121520/11492406/cdfe6b5c-97a1-11e5-96da-27d9dc18c8a4.png)

Obviously raw numbers make it harder to make comparisons when looking at the CSV...however, if you're already going to write a validation script, might as well tweak it to handle both raw numbers and percentages in producing a HTML-friendly printout. Github CSV preview is nice but I imagine the layout might get more cluttered in the near future...having raw numbers and letting the a client calculate percentages will hopefully make things slightly easier to maintain (but yeah, the tradeoff is making the CSV less readable, and more work to turn back into percentages...)

**Comment by sashaperigo** [comment]
I like this idea! It seems a lot more straightforward than what I have going on right now and shouldn't be too hard to calculate. I'll convert the all with some sort of script in the near future, and keep this issue open as a reminder for now.

**Comment by sashaperigo** [comment]
Resolved! 😊
